{"name": "未登录时进入书架", "status": "failed", "statusDetails": {"message": "AssertionError: 未登录时进入书架未跳转到登录页面\nassert 'login' not in 'http://nove...vorites.html'\n  'login' is contained here:\n    http://novel.hctestedu.com/user/login.html?originUrl=http://novel.hctestedu.com/user/favorites.html\n  ?                                 +++++", "trace": "self = <test_1.Test object at 0x000001DC253C7D30>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e24d29baa4d12c653468b72fe7a23df8\")>\n\n    @allure.title('未登录时进入书架')\n    def test_01(self, driver):\n        homePage(driver).myShelf_click()\n        url = driver.current_url\n>       assert 'login' not in url, '未登录时进入书架未跳转到登录页面'\nE       AssertionError: 未登录时进入书架未跳转到登录页面\nE       assert 'login' not in 'http://nove...vorites.html'\nE         'login' is contained here:\nE           http://novel.hctestedu.com/user/login.html?originUrl=http://novel.hctestedu.com/user/favorites.html\nE         ?                                 +++++\n\nTestCase\\test_1.py:21: AssertionError"}, "attachments": [{"name": "失败截图", "source": "b3bc47e6-c3cf-4ea2-9210-a3cdbff99208-attachment.png", "type": "image/png"}], "start": 1681895610877, "stop": 1681895613287, "uuid": "063d7aa4-175a-4e5d-919e-ccddacbf105d", "historyId": "857f429c6418f6c6f3eb73f8249723cb", "testCaseId": "fe0487d447f225a82dc0bfaabb743bf0", "fullName": "TestCase.test_1.Test#test_01", "labels": [{"name": "parentSuite", "value": "TestCase"}, {"name": "suite", "value": "test_1"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "DESKTOP-VO4GCU7"}, {"name": "thread", "value": "8584-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.test_1"}]}